/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TCC_prototipo;

import Cronometro.Cronometro;
import Cronometro.CronometroOuvinte;
import Cronometro.CronometroEvento;
import iGeradorComandos.enmTipoComando;
import java.awt.KeyboardFocusManager;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UIManager;
import util.JFrameExtensaoComandos;

/**
 * Primeiro formulário exibido pelo sistema.
 *
 * @author ASSUERO
 */
public class FrmInicio extends javax.swing.JFrame implements iGeradorComandos.iGeradorComandosOuvinte, CronometroOuvinte {

    /**
     * Objeto responsável por alterar o foco para o próximo item da tela.
     */
    KeyboardFocusManager _gerenciadorFoco = KeyboardFocusManager.getCurrentKeyboardFocusManager();
    /**
     * Cronometro responsável por exibir a janela de treinamento. Será atribuído
     * um intervalo em que o usuário deverá realizar alguma ação na tela caso
     * contrário a janela de treinamento será exibida
     */
    private Cronometro _crnTreinoIniciar = null;
    private Date _dtInicioFormulario = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
        initComponents();
        TCC.Comandos.AdicionarOuvinte(this);
        _dtInicioFormulario = new Date();
        //Se passar 30 segundos sem que o usuário faça nada, o sistema irá selecionar automaticamente o formulário de treino.
        _crnTreinoIniciar = new Cronometro(1000);
        _crnTreinoIniciar.adicionarOuvinte(this);
        // Centraliza o formulário
        this.setLocationRelativeTo(null);
    }

    @Override
    public void IntervaloOcorreu(CronometroEvento evt) {
        long lnDif = util.Data.DiferencaEmSegundos(_dtInicioFormulario, new Date());
        if (lnDif >= 30) {
            btnTreinar.doClick();
            _crnTreinoIniciar.Parar();
        } else {
            lblMsgTempoTreino.setText("Em " + (30 - lnDif) + " segundos o treino será aberto automaticamente.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        btnTreinar = new javax.swing.JButton();
        lblMsgTempoTreino = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela inicial");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setToolTipText("Abre a janela com os dispositivos.");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 122, 88));

        btnTreinar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTreinar.setText("Treinar");
        btnTreinar.setToolTipText("Abre a área para treinamento.");
        btnTreinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTreinar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 122, 88));

        lblMsgTempoTreino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMsgTempoTreino.setText("Em 30 segundos o treino será aberto automaticamente.");
        getContentPane().add(lblMsgTempoTreino, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        btnFechar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        this._crnTreinoIniciar.Parar();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        new FrmDispositivos().setVisible(true);
        FecharFrame();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnTreinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinarActionPerformed
        // TODO add your handling code here:
        this._crnTreinoIniciar.Parar();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        new FrmTreino().setVisible(true);
        FecharFrame();
    }//GEN-LAST:event_btnTreinarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        FecharFrame();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void FecharFrame() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnTreinar;
    private javax.swing.JLabel lblMsgTempoTreino;
    // End of variables declaration//GEN-END:variables

    private void MudarFoco() {
        _crnTreinoIniciar.Parar();
        JFrameExtensaoComandos.MudarFoco();
    }

    @Override
    public void ReceberComando(enmTipoComando Comando, String mensagem) {
        switch (Comando) {
            case MudarFoco:
                MudarFoco();
                break;
            case SelecionarItem:
                JFrameExtensaoComandos.SelecionarBotaoFocado(this);
                break;
            case DesconectouCabeca:

                break;
            case BateriaCritica:

                break;
            case PortaDesconectada:

                break;
        }
    }
}
