/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package movemente;

import Cronometro.Cronometro;
import Cronometro.CronometroOuvinte;
import Cronometro.CronometroEvento;
import iGeradorComandos.enmTipoComando;
import java.awt.KeyboardFocusManager;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UIManager;
import util.JFrameExtensaoComandos;

/**
 * Primeiro formulário exibido pelo sistema.
 *
 * @author ASSUERO
 */
public class FrmInicio extends javax.swing.JFrame implements iGeradorComandos.iGeradorComandosOuvinte, CronometroOuvinte {

    /**
     * Objeto responsável por alterar o foco para o próximo item da tela.
     */
    KeyboardFocusManager _gerenciadorFoco = KeyboardFocusManager.getCurrentKeyboardFocusManager();
    /**
     * Cronometro responsável por exibir a janela de treinamento. Será atribuído
     * um intervalo em que o usuário deverá realizar alguma ação na tela caso
     * contrário a janela de treinamento será exibida
     */
    private Cronometro _crnTreinoIniciar = null;
    private Date _dtInicioFormulario = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
        initComponents();
        MoveMente.Comandos.AdicionarOuvinte(this);
        _dtInicioFormulario = new Date();
        //Se passar 30 segundos sem que o usuário faça nada, o sistema irá selecionar automaticamente o formulário de treino.
        _crnTreinoIniciar = new Cronometro(1000);
        _crnTreinoIniciar.adicionarOuvinte(this);
        _crnTreinoIniciar.Iniciar();
        // Centraliza o formulário
        this.setLocationRelativeTo(null);
    }

    @Override
    public void IntervaloOcorreu(CronometroEvento evt) {
        double lnDif = util.Data.DiferencaEmSegundos(_dtInicioFormulario, new Date());
        if (lnDif >= 30) {
            btnTreinar.doClick();
            _crnTreinoIniciar.Parar();
        } else {
            lblMsgTempoTreino.setText("Em " + (int)(30 - lnDif) + " segundos o treino será aberto automaticamente.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        btnTreinar = new javax.swing.JButton();
        lblMsgTempoTreino = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        pnlMensagens = new javax.swing.JPanel();
        lblTituloMensagens = new javax.swing.JLabel();
        lblMensagensMindWave = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela inicial");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        btnIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setToolTipText("Abre a janela com os dispositivos.");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnTreinar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTreinar.setText("Treinar");
        btnTreinar.setToolTipText("Abre a área para treinamento.");
        btnTreinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinarActionPerformed(evt);
            }
        });

        lblMsgTempoTreino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMsgTempoTreino.setText("Em 30 segundos o treino será aberto automaticamente.");

        btnFechar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        pnlMensagens.setBackground(new java.awt.Color(255, 255, 255));
        pnlMensagens.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMensagens.setFocusable(false);

        lblTituloMensagens.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTituloMensagens.setText("Status Mind Wave");

        lblMensagensMindWave.setText("Mensagem");

        javax.swing.GroupLayout pnlMensagensLayout = new javax.swing.GroupLayout(pnlMensagens);
        pnlMensagens.setLayout(pnlMensagensLayout);
        pnlMensagensLayout.setHorizontalGroup(
            pnlMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensagensLayout.createSequentialGroup()
                .addGroup(pnlMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMensagensLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblTituloMensagens))
                    .addGroup(pnlMensagensLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMensagensMindWave)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pnlMensagensLayout.setVerticalGroup(
            pnlMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensagensLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblTituloMensagens)
                .addGap(16, 16, 16)
                .addComponent(lblMensagensMindWave)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(lblMsgTempoTreino))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(btnTreinar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pnlMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTreinar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(lblMsgTempoTreino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlMensagens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        this._crnTreinoIniciar.Parar();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        new FrmDispositivos().setVisible(true);
        FecharFrame();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnTreinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinarActionPerformed
        // TODO add your handling code here:
        this._crnTreinoIniciar.Parar();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        new FrmTreino().setVisible(true);
        FecharFrame();
    }//GEN-LAST:event_btnTreinarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        FecharFrame();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void FecharFrame() {
        MoveMente.Comandos.RemoverOuvinte(this);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnTreinar;
    private javax.swing.JLabel lblMensagensMindWave;
    private javax.swing.JLabel lblMsgTempoTreino;
    private javax.swing.JLabel lblTituloMensagens;
    private javax.swing.JPanel pnlMensagens;
    // End of variables declaration//GEN-END:variables

    private void MudarFoco() {
        _crnTreinoIniciar.Parar();
        JFrameExtensaoComandos.MudarFoco();
    }

    @Override
    public void ReceberComando(enmTipoComando Comando, String mensagem) {
        switch (Comando) {
            case MudarFoco:
                MudarFoco();
                break;
            case SelecionarItem:
                JFrameExtensaoComandos.SelecionarBotaoFocado(this);
                break;
            case DesconectouCabeca:

                break;
            case BateriaCritica:

                break;
            case PortaDesconectada:

                break;
        }
    }
}
