/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package movemente;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JFrame;
import javax.swing.UIManager;
import static movemente.MoveMente.IniciarConexaoHeadset;
import static movemente.MoveMente.MindWaveDesconectado;

/**
 * Formulário exibido enquanto a aplicação é carregada, antes que o primeiro
 * formulário seja aberto.
 *
 * @author ASSUERO
 */
public class FrmSplashScreen extends javax.swing.JFrame {

    private OutputStream out;

    /**
     * Creates new form FrmSplashScreen
     */
    public FrmSplashScreen() {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
        initComponents();
        this.txtPrompt.setText("Iniciando aplicativo.\n");
        // Centraliza o formulário
        this.setLocationRelativeTo(null);
        out = System.out;
        System.setOut(new PrintStream(new OutputStream() {
            public void write(int b) throws IOException {
                txtPrompt.append(String.valueOf((char) b));
            }

            public void write(byte[] b, int off, int len) {
                txtPrompt.append(new String(b, off, len));
            }
        }, true));
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowDeactivated(WindowEvent e) {
                //JFrame frame = () e.getWindow()
                if (!(e.getWindow().isVisible())) {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            System.setOut((PrintStream) out);
                        }
                    ;
                }
        );
    }
    }});
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloAplicacao = new javax.swing.JLabel();
        lblMsgAguarde = new javax.swing.JLabel();
        lblIconeAguarde = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        scpPrompt = new javax.swing.JScrollPane();
        txtPrompt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        lblTituloAplicacao.setFont(new java.awt.Font("Arial", 3, 48)); // NOI18N
        lblTituloAplicacao.setText("<html><body><u>MoveMente</u> 0.1</body></html>");

        lblMsgAguarde.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMsgAguarde.setText("Aguarde, carregando aplicativo...");

        lblIconeAguarde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movemente/Carregando.gif"))); // NOI18N

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movemente/Logo.png"))); // NOI18N

        txtPrompt.setEditable(false);
        txtPrompt.setColumns(20);
        txtPrompt.setRows(5);
        scpPrompt.setViewportView(txtPrompt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblLogo)
                        .addGap(18, 18, 18)
                        .addComponent(lblTituloAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMsgAguarde, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(lblIconeAguarde)
                                .addGap(73, 73, 73)))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpPrompt)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblTituloAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(lblIconeAguarde)
                .addGap(18, 18, 18)
                .addComponent(lblMsgAguarde)
                .addGap(18, 18, 18)
                .addComponent(scpPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSplashScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIconeAguarde;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMsgAguarde;
    private javax.swing.JLabel lblTituloAplicacao;
    private javax.swing.JScrollPane scpPrompt;
    private javax.swing.JTextArea txtPrompt;
    // End of variables declaration//GEN-END:variables
}
