/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package movemente;

import Cronometro.Cronometro;
import Cronometro.CronometroEvento;
import Cronometro.CronometroOuvinte;
import iGeradorComandos.enmTipoComando;
import iGeradorComandos.iGeradorComandosOuvinte;
import java.util.Date;
import javax.swing.JFrame;
import util.JFrameExtensaoComandos;

/**
 *
 * @author ASSUERO
 */
public class FrmTreinoClique extends javax.swing.JInternalFrame implements iGeradorComandosOuvinte, CronometroOuvinte {

    /**
     * Cronometro responsável por abrir novamente o treino de foco. O cronômetro
     * irá iniciar quando o último botão for exibido.
     */
    private Cronometro _crnEtapaReiniciar = null;
    /**
     * Data e hora em que o formulário irá iniciar.
     *
     */
    Date _dtInicioProsseguir;

    /**
     * Creates new form FrmTreinoClique
     */
    public FrmTreinoClique() {
        initComponents();
        //Os botões 2 e 3 devem iniciar desabilitados.
        btnClique2.setEnabled(false);
        btnClique3.setEnabled(false);
        btnProsseguir.setVisible(false);
        MoveMente.Comandos.AdicionarOuvinte(this);
        _crnEtapaReiniciar = new Cronometro(1000);
        _crnEtapaReiniciar.adicionarOuvinte(this);
        this.lblReiniciarTreino.setVisible(false);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        util.JFrameExtensaoComandos.ConfigurarBordaBotoes(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProsseguir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblReiniciarTreino = new javax.swing.JLabel();
        lblExplicativo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnClique1 = new javax.swing.JButton();
        btnClique2 = new javax.swing.JButton();
        btnClique3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(587, 354));
        setMinimumSize(new java.awt.Dimension(587, 354));
        setPreferredSize(new java.awt.Dimension(587, 354));

        btnProsseguir.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnProsseguir.setText("Prosseguir");
        btnProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsseguirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel2.setText("ETAPA 2 - TREINANDO O CLIQUE");

        lblReiniciarTreino.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblReiniciarTreino.setText("Aguarde 25 segundos para esta etapa ser reiniciada.");

        lblExplicativo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblExplicativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExplicativo.setText("<html>Para mudar o foco de um botão para outro, <br/>basta piscar o olho com força uma vez em um intervalo de 3 segundos.</html>");

        jPanel1.setMaximumSize(new java.awt.Dimension(556, 135));
        jPanel1.setMinimumSize(new java.awt.Dimension(556, 135));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(556, 135));

        btnClique1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnClique1.setText("Clique 1");
        btnClique1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClique1ActionPerformed(evt);
            }
        });

        btnClique2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnClique2.setText("Clique 2");
        btnClique2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClique2ActionPerformed(evt);
            }
        });

        btnClique3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnClique3.setText("Clique 3");
        btnClique3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClique3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClique1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClique2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(btnClique3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClique2)
                    .addComponent(btnClique1))
                .addGap(33, 33, 33)
                .addComponent(btnClique3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblExplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReiniciarTreino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReiniciarTreino)
                    .addComponent(btnProsseguir))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre a tela para treinar o foco e o clique e fecha a tela atual
     *
     * @param evt
     */
    private void btnProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsseguirActionPerformed
        // TODO add your handling code here:
        MoveMente.Container.AdicionarFrame(new FrmTreinoFocoClique());
        FecharFrame();
    }//GEN-LAST:event_btnProsseguirActionPerformed

    private void btnClique1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClique1ActionPerformed
        btnClique2.setEnabled(true);
        btnClique2.requestFocus();
        btnClique1.setFocusable(false);
    }//GEN-LAST:event_btnClique1ActionPerformed

    private void btnClique2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClique2ActionPerformed
        btnClique3.setEnabled(true);
        btnClique3.requestFocus();
        btnClique2.setFocusable(false);
    }//GEN-LAST:event_btnClique2ActionPerformed

    private void btnClique3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClique3ActionPerformed
        btnProsseguir.setVisible(true);
        btnProsseguir.requestFocus();
        _crnEtapaReiniciar.Iniciar();
        _dtInicioProsseguir = new Date();
        this.lblReiniciarTreino.setVisible(true);
        btnClique3.setFocusable(false);
    }//GEN-LAST:event_btnClique3ActionPerformed

    private void FecharFrame() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        _crnEtapaReiniciar.Parar();
        _crnEtapaReiniciar.removerOuvinte(this);
        MoveMente.Comandos.RemoverOuvinte(this);
        this.hide();
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTreinoClique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTreinoClique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTreinoClique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTreinoClique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTreinoClique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClique1;
    private javax.swing.JButton btnClique2;
    private javax.swing.JButton btnClique3;
    private javax.swing.JButton btnProsseguir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExplicativo;
    private javax.swing.JLabel lblReiniciarTreino;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ReceberComando(enmTipoComando Comando, String mensagem) {
        switch (Comando) {
            case MudarFoco:
                break;
            case SelecionarItem:
                JFrameExtensaoComandos.SelecionarBotaoFocado(this);
                break;
            case DesconectouCabeca:
                break;
            case BateriaCritica:
                break;
            case PortaDesconectada:
                break;
        }
    }

    @Override
    public void IntervaloOcorreu(CronometroEvento evt) {
        double lnDif = util.Data.DiferencaEmSegundos(_dtInicioProsseguir, new Date());
        if (lnDif >= 25) {
            new FrmTreinoClique().setVisible(true);
            FecharFrame();
        } else {
            lblReiniciarTreino.setText("Em " + (int) (25 - lnDif) + " segundos esta etapa será reiniciada.");
        }
    }
}
